In [1]:
x=int(input("enter a number:"))
y=int(input("enter second number:"))
if(x==12):
    print('its 12')
else:
    print(x+y)

enter a number:3
enter second number:2
5


In [3]:
x=input("enter the user name:")
y=input("enter a password:")
if(x=="jayesh") and (y=="h1"):
    print('welcome')
else:
    print("try again")   

enter the user name:jayesh
enter a password:h2
try again


In [4]:
for i in range(10):
    print (i)

0
1
2
3
4
5
6
7
8
9


In [5]:
z=['jayesh','kaustubh','jignesh']
for i in range(len(z)):

    print(z)


['jayesh', 'kaustubh', 'jignesh']
['jayesh', 'kaustubh', 'jignesh']
['jayesh', 'kaustubh', 'jignesh']


In [9]:
a=[]
z=['jayesh','kaustubh','jignesh']
for i in z:
  print(str(len(z)),"i",i)

3 i jayesh
3 i kaustubh
3 i jignesh


In [12]:
#funtion

#function without parameters
def name():
    print('jayesh')

In [10]:
#function with parameters
def name(x):
    print('jayesh and',x)

name('mahesh')

name('ramesh')

jayesh and mahesh
jayesh and ramesh


In [13]:
import numpy

In [14]:
import numpy as np

In [16]:
x = np.array([10,11,12,13])
print(x)

[10 11 12 13]


In [19]:
x = np.array([[10,11,12,13],[14,15,16,17]])
print(x)

[[10 11 12 13]
 [14 15 16 17]]


In [32]:
# n dimension
x = np.array([[10,11,12,13],[14,15,16,17],[18,19,20,21]])
print(x,ndim)


NameError: ignored

In [21]:
print(x)
print(x.sum())
#print(x.prod())
print(x.max())
print(x.min())
print(x.argmax())
print(x.argmin())

[[10 11 12 13]
 [14 15 16 17]]
108
17
10
7
0


In [23]:
x.shape

(3, 4)

In [24]:
b = x.reshape(4,3)

In [25]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [26]:
x.transpose()

array([[10, 14, 18],
       [11, 15, 19],
       [12, 16, 20],
       [13, 17, 21]])

In [30]:
a = 0

a = np.arange(16).reshape(4,4)

In [31]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])